name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build release
        run: ./gradlew assembleRelease

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: App Center Distribute

        run: |
          npm install -g appcenter-cli
          appcenter distribute release --app Summer-Camp-AND-Newton/Summer-camp-Comms_build -r "For QA- New code merged to master" --file app/build/outputs/apk/release/*.apk --group "QA" --token ${{secrets.APP_CENTER_TOKEN}}
          
   

